version: 2.1
orbs:
  node: circleci/node@3.0.0
  aws-cli: circleci/aws-cli@1.3.0
jobs:
  build:
    executor: aws-cli/default
    docker:
      - image: circleci/node:12.20.1
    working_directory: /tmp/repo
    steps:
      - checkout
      - aws-cli/setup
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: "Install NPM Packages"
          command: "npm install"
      - run:
          name: "Print 'Hello World'"
          command: "echo 'Hello World'"
      - run:
          name: "Sync Files to AWS S3"
          command: aws s3 sync . s3://myreact-cicd --exclude "*node_modules/*"
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
