version: '2.1'
orbs:
  aws-s3: circleci/aws-s3@3.1
jobs:
  build:
    docker:
      - image: 'cimg/python:3.10'
    steps:
      - checkout
      - run: mkdir bucket && echo "lorem ipsum" > bucket/build_asset.txt
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: bucket
          role-arn: 'arn:aws:iam::123456789012/role/VALID-S3-ROLE'
          to: 's3://myreact-cicd/app'
      - aws-s3/copy:
          arguments: '--dryrun'
          from: bucket/build_asset.txt
          install-aws-cli: false
          to: 's3://myreact-cicd'
workflows:
  s3-example:
    jobs:
      - build
